//BROWSER SELECTION
browser=chrome
// URL SEND
url=https://www.demoblaze.com/
urlto="www.youtupe.com"
//APPLICATION USER ID NAME
username=saan
password=saan@3006
name=saan
country=india
city=sivakasi
cardNum=32318468149146
month=jan
year=2026
